const fieldsOfStudy = [
    // Adjuncts
    // { category: 'Adjuncts', isHeading: true },
    'Agriculture/Vet Med',
    'Business',
    'Culinary Arts/Food Management',
    'Curriculum & Education',
    'Engineering',
    'Fine Arts - Dance',
    'Fine Arts - Drama/Theater',
    'Fine Arts - Music',
    'Fine Arts - Visual Arts',
    'Fine Arts - Other',
    'Health Sciences',
    'Humanities - English',
    'Humanities - Foreign Languages',
    'Humanities - History',
    'Humanities - Literature',
    'Humanities - Philosophy',
    'Humanities - Other',
    'Law',
    'Medicine',
    'Pharmacy',
    'Sciences - Biological',
    'Sciences - Chemistry',
    'Sciences - Computer Science',
    'Sciences - Math',
    'Sciences - Physics',
    'Sciences - Other',
    'Social Sciences - Communication',
    'Social Sciences - Economics',
    'Social Sciences - Geography',
    'Social Sciences - Political Science',
    'Social Sciences - Psychology',
    'Social Sciences - Sociology',
    'Social Sciences - Other',
    'Vocational/Technical',
  
    // Agriculture
    // { category: 'Agriculture', isHeading: true },
    'Agricultural - General',
    'Agricultural Extension',
    'Agronomy/Plant & Soil Sciences',
    'Animal Genomics',
    'Animal Science',
    'Biosystems Engineering',
    'Botany',
    'Dairy Science',
    'Economics',
    'Engineering/Engineering Extension',
    'Entomology',
    'Environmental Science & Ecology',
    'Food & Nutritional Science',
    'Forest Ecology & Management',
    'Horticulture',
    'Landscape Architecture',
    'Land & Water Resource Engineering',
    'Meat Science',
    'Pathobiology',
    'Plant Genetics',
    'Plant Pathology',
    'Poultry Science',
    'Statistics',
    'Veterinary Science/Medicine',
    'Viticulture and Enology',
    'Water Management/Policy',
    'Zoology/Genetics',
  
    // Business
    // { category: 'Business', isHeading: true },
    'Business - General',
    'Accounting and/or Taxes',
    'Arts Administration',
    'Business Communications',
    'Business Ethics',
    'Business Law',
    'Construction Management',
    'Decision Sciences',
    'Economics',
    'Entrepreneurship',
    'Finance',
    'General Management',
    'Health Systems Management',
    'Hospitality/Tourism Management',
    'Human Resources',
    'Insurance/Risk Management',
    'International Business',
    'Logistics/Supply Chain Management',
    'Management Information Systems - All',
    'Marketing',
    'MBA & Executive MBA',
    'Nonprofit Organizations',
    'Organizational Studies',
    'Production/Operations Management',
    'Public Policy & Administration',
    'Real Estate',
    'Quantitative Analysis',
    'Sport Management',
    'Statistics & Actuarial Science',
    'Technology & Information Management',
  
    // Community Colleges
    // { category: 'Community Colleges', isHeading: true },
    'Administration - Executive',
    'Administration - Academic Unit',
    'Administration - Accounting & Finance',
    'Administration - Counseling Services',
    'Administration - Human Resources',
    'Administration - Student Affairs',
    'Administration - Undergraduate Education',
    'Administration - Other',
    'Agriculture/Vet Med',
    'Business',
    'Culinary Arts/Food Management',
    'Education',
    'Engineering',
    'Fine Arts - Dance',
    'Fine Arts - Drama/Theater',
    'Fine Arts - Music',
    'Fine Arts - Visual Arts',
    'Fine Arts - Other',
    'Health Sciences',
    'Humanities - English',
    'Humanities - Foreign Languages',
    'Humanities - History',
    'Humanities - Literature',
    'Humanities - Philosophy',
    'Humanities - Other',
    'Law',
    'Medicine',
    'Sciences - Biological',
    'Sciences - Chemistry',
    'Sciences - Computer Science',
    'Sciences - Math',
    'Sciences - Physics',
    'Sciences - Other',
    'Social Sciences - Communication',
    'Social Sciences - Economics',
    'Social Sciences - Geography',
    'Social Sciences - Political Science',
    'Social Sciences - Psychology',
    'Social Sciences - Sociology',
    'Social Sciences - Other',
    'Vocational/Technical',
  
    // Curriculum & Education
    // { category: 'Curriculum & Education', isHeading: true },
    'Education - General',
    'Administration/Supervision',
    'Adult and Distance Education',
    'Art Education',
    'Audiology/Speech Pathology',
    'Counseling/Human Services',
    'Childhood/Youth Education',
    'Curriculum/Instruction',
    'Education Policy',
    'Educational Psychology/Behavior Analysis',
    'Educational Technology',
    'Elementary Education',
    'English Education',
    'English as a Second Language',
    'Health & Human Performance',
    'Higher Education Administration',
    'Human Development',
    'Information Studies',
    'Instructional Design/Technology',
    'Math Education',
    'Middle School',
    'Music Education',
    'Reading/Developmental Education',
    'Organization and Leadership',
    'Physical Education & Kinesiology',
    'Professional Development',
    'Rehabilitation Counseling/Psychology',
    'Science Education',
    'Secondary Education',
    'Social Foundations',
    'Sociology',
    'Special Education',
    'Sports Studies',
    'Teacher Education',
    'Urban Education',
    'Vocational/Technical',
  
    // Dentistry
    // { category: 'Dentistry', isHeading: true },
    'Dentistry - General',
    'Biological/Materials Sciences',
    'Cariology',
    'Dental Anesthesiology',
    'Dental Hygiene',
    'Dental Technology',
    'Dentistry & Stomatology',
    'Endodontics',
    'Family Dentistry',
    'Gerodontology',
    'Oral & Maxillofacial Surgery',
    'Oral Biology',
    'Oral Medicine/Pathology/Oncology',
    'Oral Radiology',
    'Orthodontics',
    'Pediatric Dentistry',
    'Periodontics/Periodontology',
    'Preventive & Community Dentistry',
    'Prosthodontics/Restorative Dentistry',
    'Public Health/Epidemiology',
  
    // Engineering
    // { category: 'Engineering', isHeading: true },
    'Engineering - Other',
    'Aerospace/Aeronautical/Astronautics',
    'Agricultural',
    'Architectural (Building & Construction)',
    'Bioengineering (all Bio-related fields)',
    'Chemical/Petroleum',
    'Civil Engineering',
    'Construction Engineering/Management',
    'Computer Science',
    'Computer Engineering',
    'Education Systems & Design',
    'Electrical and/or Electronics',
    'Energy Technology',
    'Engineering Mechanics',
    'Engineering Physics',
    'Ecological and Environmental',
    'Food Process Engineering',
    'Geomatics',
    'Geotechnical',
    'Human Factors Engineering/Ergonomics',
    'Industrial & Systems Engineering',
    'Manufacturing & Quality Engineering',
    'Material/Metallurgy',
    'Mechanical Engineering',
    'Mechatronics',
    'Mining/Minerals',
    'Naval Architecture & Marine Engineering',
    'Nuclear',
    'Ocean Engineering',
    'Optics & Optical Engineering',
    'Polymer Science',
    'Pulp & Paper Science',
    'Risk Management & Financial Engineering',
    'Robotics',
    'Structural Engineering',
    'Sustainable Engineering',
    'Textile Engineering',
    'Transportation Engineering',
    'Water Resources Engineering',
  
    // Fine Arts
    // { category: 'Fine Arts', isHeading: true },
    'Fine Arts - General',
    'Architecture/Landscape Architecture',
    'Art Administration',
    'Art Education',
    'Art History',
    'Art - General',
    'Art - Ceramics',
    'Art - Painting/Drawing',
    'Art - Photography',
    'Art - Printmaking',
    'Art - Sculpture',
    'Communications/Information Systems',
    'Culinary Arts/Gastronomy',
    'Dance',
    'Design - Fashion & Textile Design',
    'Design - Graphic Design/Illustration',
    'Design - Industrial Art/Design',
    'Design - Interior Design',
    'Design - Jewelery Design',
    'Design - Product Design',
    'Digital Media',
    'Drama/Theater/Theater Education',
    'Film/Video',
    'Game Design/Animation',
    'Music Education',
    'Music Industry Studies',
    'Music - General',
    'Music - Classical',
    'Music - Composition',
    'Music - Conducting',
    'Music - Ethnomusicology',
    'Music - Jazz',
    'Music - Musicology/Music History',
    'Music - Vocal',
    'Music - Orchestra/Symphony',
    'Music - Piano/Organ/Keyboard',
    'Music - Psychology',
    'Music - Scientific Study/Theory',
    'Music - Song Performance',
    'Performance Studies',
    'Television/Media Studies',
  
    // Health Sciences
    // { category: 'Health Sciences', isHeading: true },
    'Health Sciences - General',
    'Acupuncture & Oriental Medicine',
    'Allied Health',
    'Anatomy & Cell Biology',
    'Anesthesiology',
    'Biochemistry',
    'Bioinformatics',
    'Biomedical Engineering',
    'Biomedical Science',
    'Biostatistics',
    'Cardiology',
    'Clinical Medicine',
    'Clinical Psychology',
    'Community Health',
    'Cytology/Histology',
    'Dentistry',
    'Dermatology',
    'Emergency Medicine',
    'Endocrinology',
    'Epidemiology',
    'Family Medicine',
    'Forensic Medicine',
    'Gastroenterology',
    'Genetic Counseling',
    'Geriatrics',
    'Health Education/Promotion',
    'Health Informatics',
    'Health Policy & Management',
    'Health Services Administration',
    'Hematology',
    'Immunology',
    'Infectious Diseases',
    'Internal Medicine',
    'Kinesiology',
    'Medical Physics',
    'Medical Technology',
    'Medicine - General',
    'Microbiology',
    'Nephrology',
    'Neurology',
    'Nuclear Medicine',
    'Nutrition',
    'Obstetrics/Gynecology',
    'Occupational Therapy',
    'Oncology',
    'Ophthalmology',
    'Optometry',
    'Orthopedics',
    'Osteopathy',
    'Otolaryngology',
    'Pain Management',
    'Pathology',
    'Pediatrics',
    'Pharmacology/Toxicology',
    'Physical Therapy',
    'Physiology',
    'Plastic Surgery',
    'Podiatry',
    'Preventive Medicine',
    'Psychiatry',
    'Public Health',
    'Pulmonary Medicine',
    'Radiation Oncology',
    'Radiology',
    'Rehabilitation Medicine',
    'Reproductive Medicine',
    'Respiratory Therapy',
    'Rheumatology',
    'Social Work',
    'Speech & Hearing Science',
    'Sports Medicine',
    'Surgery - General',
    'Surgery - Cardiothoracic',
    'Surgery - Neurological',
    'Surgery - Orthopedic',
    'Surgery - Plastic & Reconstructive',
    'Surgery - Transplantation',
    'Surgery - Vascular',
    'Toxicology',
    'Urology',
    'Veterinary Medicine',
    'Women\'s Health',
  
    // Humanities
    // { category: 'Humanities', isHeading: true },
    'Humanities - General',
    'Art History',
    'Comparative Literature',
    'Creative Writing',
    'English Literature',
    'Film/Cinema Studies',
    'Folklore',
    'French Literature',
    'German Literature',
    'History - General',
    'History - African',
    'History - American',
    'History - Asian',
    'History - European',
    'History - Latin American',
    'History - Middle East',
    'History - Military',
    'History - Women',
    'Humanities - Women',
    'Interdisciplinary Studies',
    'Italian Literature',
    'Jewish Studies',
    'Journalism',
    'Liberal Arts',
    'Linguistics',
    'Media Studies',
    'Medieval Studies',
    'Museum Studies',
    'Music History & Literature',
    'Philosophy',
    'Religious Studies',
    'Russian Literature',
    'Spanish Literature',
    'Speech Communication',
    'Theater Studies',
  
    // Journalism
    // { category: 'Journalism', isHeading: true },
    'Journalism - General',
    'Broadcast Journalism',
    'Business Journalism',
    'Community Journalism',
    'Digital Media/Internet Journalism',
    'Editing/Editing/Writing/Publishing',
    'International/Foreign Affairs Journalism',
    'Investigative Journalism',
    'Journalism & Political Science',
    'Journalism Education',
    'Journalism Ethics',
    'Magazine Writing',
    'Media Management',
    'News Reporting',
    'Photojournalism',
    'Public Relations',
    'Science & Environmental Journalism',
    'Social Media & Online Communities',
    'Sports Journalism',
    'Visual Journalism',
    'Women in Journalism',
  
    // Law
    // { category: 'Law', isHeading: true },
    'Law - General',
    'Alternative Dispute Resolution',
    'Antitrust/Trade Regulation',
    'Bankruptcy & Debt',
    'Civil Rights',
    'Commercial Law',
    'Comparative Law',
    'Constitutional Law',
    'Corporate Law & Securities Regulation',
    'Criminal Justice/Criminology',
    'Dispute Resolution',
    'Employment & Labor Law',
    'Environmental/Natural Resources Law',
    'Family Law/Juvenile Law',
    'Health Law/Bioethics',
    'Human Rights Law',
    'Immigration Law',
    'Insurance Law',
    'Intellectual Property Law',
    'International Law',
    'Judicial Studies',
    'Juvenile Justice',
    'Land Use Planning & Zoning',
    'Law & Business',
    'Legal Writing & Research',
    'Litigation & Trial Advocacy',
    'Public Interest Law',
    'Real Estate Law',
    'Sports & Entertainment Law',
    'Taxation',
    'Technology Law',
    'Torts',
    'Trial Advocacy',
  
    // Medicine
    // { category: 'Medicine', isHeading: true },
    'Medicine - General',
    'Addiction Medicine',
    'Allergy & Immunology',
    'Anesthesiology',
    'Bioethics/Medical Ethics',
    'Cardiology',
    'Clinical Trials',
    'Critical Care Medicine',
    'Dermatology',
    'Emergency Medicine',
    'Endocrinology',
    'Epidemiology',
    'Family Medicine',
    'Forensic Medicine',
    'Gastroenterology',
    'General Practice/Family Medicine',
    'Genetics',
    'Geriatrics',
    'Gynecology & Obstetrics',
    'Health Administration',
    'Hematology',
    'Infectious Disease',
    'Internal Medicine',
    'Nephrology',
    'Neurology',
    'Nuclear Medicine',
    'Nutrition',
    'Oncology',
    'Ophthalmology',
    'Orthopedics',
    'Otolaryngology',
    'Pain Medicine',
    'Pathology',
    'Pediatrics',
    'Pharmacology',
    'Physical Medicine & Rehabilitation',
    'Plastic Surgery',
    'Podiatry',
    'Preventive Medicine',
    'Psychiatry',
    'Pulmonary Medicine',
    'Radiation Oncology',
    'Radiology',
    'Rheumatology',
    'Sports Medicine',
    'Surgery - General',
    'Surgery - Cardiovascular/Thoracic',
    'Surgery - Neurological',
    'Surgery - Orthopedic',
    'Surgery - Pediatric',
    'Surgery - Plastic/Reconstructive',
    'Surgery - Transplant',
    'Surgery - Urology',
    'Surgery - Vascular',
    'Toxicology',
    'Trauma Surgery',
    'Travel Medicine',
    'Urology',
    'Veterinary Medicine',
  
    // Pharmacy
    // { category: 'Pharmacy', isHeading: true },
    'Pharmacy - General',
    'Clinical Pharmacy',
    'Community Pharmacy',
    'Geriatric Pharmacy',
    'Health Services Pharmacy',
    'Hospital Pharmacy',
    'Industrial Pharmacy',
    'Managed Care Pharmacy',
    'Pharmaceutical Chemistry',
    'Pharmaceutical Sciences',
    'Pharmaceutics/Pharmacology',
    'Pharmacognosy',
    'Pharmacotherapy',
    'Pharmacy Administration',
    'Pharmacy Informatics',
    'Psychopharmacology',
    'Toxicology',
  
    // Sciences
    // { category: 'Sciences', isHeading: true },
    'Sciences - General',
    'Anthropology',
    'Astronomy',
    'Atmospheric Sciences',
    'Bacteriology',
    'Biochemistry',
    'Bioinformatics',
    'Biological Sciences',
    'Biophysics',
    'Botany',
    'Chemistry',
    'Climatology/Meteorology',
    'Computational Biology',
    'Earth Sciences',
    'Ecology',
    'Entomology',
    'Environmental Sciences',
    'Evolutionary Biology',
    'Genetics',
    'Geography',
    'Geology',
    'Geophysics',
    'Hydrology',
    'Immunology',
    'Marine Biology',
    'Mathematics',
    'Microbiology',
    'Molecular Biology',
    'Neuroscience',
    'Oceanography',
    'Paleontology',
    'Parasitology',
    'Physical Sciences',
    'Physics',
    'Physiology',
    'Plant Biology',
    'Quantitative Biology',
    'Science - Women',
    'Statistics',
    'Toxicology',
    'Virology',
    'Wildlife Biology',
    'Zoology',
  
    // Social Sciences
    // { category: 'Social Sciences', isHeading: true },
    'Social Sciences - General',
    'Anthropology',
    'Archaeology',
    'Criminal Justice',
    'Economics',
    'Education',
    'Geography',
    'History',
    'International Relations',
    'Law',
    'Linguistics',
    'Political Science',
    'Psychology',
    'Public Administration',
    'Social Work',
    'Sociology',
    'Urban Planning',
  
    // Vocational/Technical
    // { category: 'Vocational/Technical', isHeading: true },
    'Vocational/Technical - General',
    'Accounting & Financial Management',
    'Automotive Technology',
    'Aviation/Aerospace Technology',
    'Building & Construction Trades',
    'Business & Office Administration',
    'Carpentry & Woodworking',
    'Child Care & Development',
    'Computer Technology',
    'Cosmetology & Personal Grooming',
    'Culinary Arts',
    'Drafting & Design',
    'Electrical & Electronics Technology',
    'Fashion Design & Merchandising',
    'Fire Science & Emergency Management',
    'Heating, Ventilation, & Air Conditioning (HVAC)',
    'Hospitality Management',
    'HVAC & Environmental Controls',
    'Industrial Technology',
    'Information Technology',
    'Law Enforcement & Criminal Justice',
    'Legal & Court Reporting',
    'Machine Shop & Tool Technology',
    'Mechanical Drafting (CAD/CAM)',
    'Medical & Health Services Management',
    'Nursing',
    'Paralegal & Legal Assistant',
    'Physical Therapy Technology',
    'Plumbing Technology',
    'Precision Production Trades',
    'Radio & Television Broadcasting',
    'Refrigeration Technology',
    'Restaurant & Food Services Management',
    'Robotics & Automation Technology',
    'Technical Communications',
    'Telecommunications Technology',
    'Truck Driving & Transportation',
    'Veterinary Technology',
    'Visual Communications',
    'Welding',
  
    // Women's Studies
    // { category: "Women's Studies", isHeading: true },
    "Women's Studies - General",
    'Feminism',
    'Gender & Sexuality Studies',
    'Women in Business',
    'Women in Media',
    'Women in Science',
    'Women in Technology',
  
    // Writing
    // { category: 'Writing', isHeading: true },
    'Writing - General',
    'Business Writing',
    'Creative Writing',
    'Fiction Writing',
    'Freelance Writing',
    'Nonfiction Writing',
    'Poetry Writing',
    'Professional Writing',
    'Screenwriting',
    'Technical Writing',
  
    // Other
    // { category: 'Other', isHeading: true },
    'Adult Education',
    'Anthropology',
    'Archaeology',
    'Arts Management',
    'Childhood Education',
    'Cognitive Studies',
    'College Student Personnel',
    'Continuing Education',
    'Curriculum & Instruction',
    'Distance Education',
    'Early Childhood Education',
    'Education',
    'Educational Leadership',
    'Educational Psychology',
    'Elementary Education',
    'English Education',
    'Environmental Education',
    'ESL Education',
    'Fine Arts Education',
    'Gifted Education',
    'Higher Education',
    'History Education',
    'Instructional Technology',
    'International Education',
    'Language Education',
    'Learning Disabilities Education',
    'Library Science',
    'Mathematics Education',
    'Middle School Education',
    'Multicultural Education',
    'Music Education',
    'Outdoor Education',
    'Philosophy of Education',
    'Physical Education',
    'Psychology of Education',
    'Reading & Literacy Education',
    'Religious Education',
    'School Counseling',
    'School Psychology',
    'Science Education',
    'Secondary Education',
    'Social Foundations of Education',
    'Social Studies Education',
    'Special Education',
    'Teacher Education',
    'Teaching English as a Second Language',
    'Technology & Education',
    'Vocational Education',
    'Women\'s Studies',
  
    // Vocational/Technical
    // { category: 'Vocational/Technical', isHeading: true },
    'Vocational/Technical - General',
    'Accounting & Financial Management',
    'Automotive Technology',
    'Aviation/Aerospace Technology',
    'Building & Construction Trades',
    'Business & Office Administration',
    'Carpentry & Woodworking',
    'Child Care & Development',
    'Computer Technology',
    'Cosmetology & Personal Grooming',
    'Culinary Arts',
    'Drafting & Design',
    'Electrical & Electronics Technology',
    'Fashion Design & Merchandising',
    'Fire Science & Emergency Management',
    'Heating, Ventilation, & Air Conditioning (HVAC)',
    'Hospitality Management',
    'HVAC & Environmental Controls',
    'Industrial Technology',
    'Information Technology',
    'Law Enforcement & Criminal Justice',
    'Legal & Court Reporting',
    'Machine Shop & Tool Technology',
    'Mechanical Drafting (CAD/CAM)',
    'Medical & Health Services Management',
    'Nursing',
    'Paralegal & Legal Assistant',
    'Physical Therapy Technology',
    'Plumbing Technology',
    'Precision Production Trades',
    'Radio & Television Broadcasting',
    'Refrigeration Technology',
    'Restaurant & Food Services Management',
    'Robotics & Automation Technology',
    'Technical Communications',
    'Telecommunications Technology',
    'Truck Driving & Transportation',
    'Veterinary Technology',
    'Visual Communications',
    'Welding',
  
    // Women's Studies
    // { category: "Women's Studies", isHeading: true },
    "Women's Studies - General",
    'Feminism',
    'Gender & Sexuality Studies',
    'Women in Business',
    'Women in Media',
    'Women in Science',
    'Women in Technology',
  
    // Writing
    // { category: 'Writing', isHeading: true },
    'Writing - General',
    'Business Writing',
    'Creative Writing',
    'Fiction Writing',
    'Freelance Writing',
    'Nonfiction Writing',
    'Poetry Writing',
    'Professional Writing',
    'Screenwriting',
    'Technical Writing',
  
    // Other
    // { category: 'Other', isHeading: true },
    'Adult Education',
    'Cognitive Studies',
    'Continuing Education',
    'Curriculum & Instruction',
    'Distance Education',
    'Early Childhood Education',
    'Educational Leadership',
    'Educational Psychology',
    'Elementary Education',
    'English Education',
    'Environmental Education',
    'ESL Education',
    'Fine Arts Education',
    'Gifted Education',
    'Higher Education',
    'Instructional Technology',
    'International Education',
    'Language Education',
    'Learning Disabilities Education',
    'Library Science',
    'Mathematics Education',
    'Middle School Education',
    'Multicultural Education',
    'Music Education',
    'Outdoor Education',
    'Philosophy of Education',
    'Physical Education',
    'Psychology of Education',
    'Reading & Literacy Education',
    'Religious Education',
    'School Counseling',
    'School Psychology',
    'Science Education',
    'Secondary Education',
    'Social Foundations of Education',
    'Social Studies Education',
    'Special Education',
    'Teacher Education',
    'Teaching English as a Second Language',
    'Technology & Education',
    'Vocational Education',
    'Women\'s Studies'
  ]


  export default fieldsOfStudy;
  
  