const qualificationTypes = [
    "Primary School Certificate/Diploma",
    "Middle School Certificate",
    "High School Diploma/Certificate",
    "Secondary School Certificate (SSC)",
    "General Certificate of Secondary Education (GCSE)",
    "O-Level (Ordinary Level) Certificate",
    "A-Level (Advanced Level) Certificate",
    "International Baccalaureate (IB) Diploma",
    "Vocational and Technical Qualification",
    "Associate Degree",
    "Bachelor of Arts (BA)",
    "Bachelor of Science (BSc)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Engineering (BEng)",
    "Bachelor of Laws (LLB)",
    "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
    "Bachelor of Education (BEd)",
    "Bachelor of Technology (BTech)",
    "Postgraduate Certificate",
    "Postgraduate Diploma",
    "Graduate Certificate",
    "Graduate Diploma",
    "Master of Arts (MA)",
    "Master of Science (MSc)",
    "Master of Business Administration (MBA)",
    "Master of Fine Arts (MFA)",
    "Master of Education (MEd)",
    "Master of Laws (LLM)",
    "Master of Engineering (MEng)",
    "Master of Public Health (MPH)",
    "Master of Social Work (MSW)",
    "Master of Philosophy (MPhil)",
    "Doctor of Philosophy (PhD)",
    "Doctor of Education (EdD)",
    "Doctor of Business Administration (DBA)",
    "Doctor of Medicine (MD)",
    "Chartered Accountant (CA)",
    "Certified Public Accountant (CPA)",
    "Chartered Financial Analyst (CFA)",
    "Project Management Professional (PMP)",
    "Chartered Engineer (CEng)",
    "Licensed Professional Engineer (PE)",
    "Certified Information Systems Security Professional (CISSP)",
    "Legal Practice Course (LPC)",
    "Bar Professional Training Course (BPTC)",
    "Professional Diploma",
    "Professional Certificate",
    "Continuing Education Units (CEU)",
    "Certified Specialist",
    "European Baccalaureate (EB)",
    "Baccalauréat (France)",
    "Abitur (Germany)",
    "Matura (Switzerland, Austria, Italy)",
    "Gaokao (China)",
    "Kankor (Afghanistan)"
]

export default qualificationTypes