
const specialisations = [
        "Academic research",
        "Accounting",
        "Accounting & finance",
        "Administration",
        "Advertising",
        "Aerospace",
        "Agriculture",
        "Agriculture, animals & plants",
        "Architecture",
        "Armed forces",
        "Automotive",
        "Banking, insurance & financial services",
        "Building services",
        "Business & systems analysis",
        "Charities & voluntary sector",
        "Charity, public & civil service",
        "Chemical",
        "Civil & structural",
        "Civil services",
        "Communications & telecoms",
        "Compliance & regulation",
        "Construction",
        "Consulting",
        "Creative arts & design",
        "Data science",
        "Dental",
        "Design",
        "Digital",
        "Education",
        "Electronic & electrical",
        "Emergency services",
        "Energy, natural resources & utilities",
        "Engineering",
        "Environmental",
        "Event management",
        "Film and cinematography",
        "Food",
        "HR & recruitment",
        "Healthcare",
        "Higher education",
        "Hospitality, sport, leisure & tourism",
        "Hotel management",
        "Human resource management",
        "Information services",
        "Insurance",
        "Investment banking & fund management",
        "Journalism",
        "Languages, libraries & culture",
        "Law",
        "Law barristers",
        "Law enforcement",
        "Law solicitors",
        "Law, legal services & patents",
        "Leisure & tourism",
        "Management",
        "Management & business",
        "Management consulting",
        "Manufacturing & processing",
        "Manufacturing/production/process",
        "Marketing",
        "Marketing, advertising & PR",
        "Materials & metals",
        "Mechanical",
        "Media",
        "Media, journalism & publishing",
        "Medical",
        "Medical, healthcare & dental",
        "Merchandising",
        "Museums, libraries & heritage",
        "Network engineering",
        "Pharmaceutical",
        "Procurement",
        "Procurement & supply chain",
        "Product R&D",
        "Property asset management",
        "Property consultant",
        "Property, construction & QS",
        "Public relations & communications",
        "Public service",
        "Publishing",
        "Recruitment",
        "Retail",
        "Retail, business & commercial services",
        "Sales",
        "Sales & lettings",
        "Science, R&D, food industry",
        "Security & intelligence",
        "Social & market research",
        "Social care",
        "Social, community & youth",
        "Software engineering",
        "Software testing",
        "Sports",
        "Supply chain",
        "Surveying",
        "Teaching",
        "Teaching & education",
        "Technical consultancy",
        "Technical sales",
        "Technical support",
        "Technology",
        "Training & development",
        "Veterinary",
        "Warehouse management",
        "Web development"
      ];
      
      export default specialisations;
      