const techstacks = [
    "Java",
    "JavaScript",
    "Python",
    "Ruby",
    "C#",
    "C++",
    "PHP",
    "Swift",
    "Kotlin",
    "TypeScript",
    "Go",
    "Rust",
    "Scala",
    "HTML/CSS",
    "React.js",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Spring Boot",
    "Django",
    "Ruby on Rails",
    "ASP.NET",
    "Laravel",
    "Flask",
    "Spring Framework",
    "Hibernate",
    "JSP",
    "Thymeleaf",
    "Play Framework",
    "React Native",
    "Flutter",
    "SwiftUI",
    "Android",
    "iOS",
    "Firebase",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Oracle",
    "Microsoft SQL Server",
    "Redis",
    "Elasticsearch",
    "AWS",
    "Google Cloud",
    "Microsoft Azure",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Git",
    "GraphQL",
    "RESTful APIs",
    "Microservices",
    "Serverless",
    "Machine Learning",
    "Data Science",
    "Artificial Intelligence",
    "Natural Language Processing",
    "Big Data",
    "Blockchain",
    "DevOps",
    "Continuous Integration",
    "Continuous Deployment",
    "Agile",
    "Scrum",
    "Kanban",
    "Extreme Programming (XP)",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Pair Programming",
    "Domain-Driven Design (DDD)",
    "Event-Driven Architecture (EDA)",
    "SOLID Principles",
    "Design Patterns",
  ];

  export default techstacks;