const imageUrl = "https://fakeimg.pl/270x270";
const JobFakeData = [
  {
    companyName: "TechCorp",
    jobRole: "Frontend Developer",
    contract: "Full-Time",
    place: "New York, NY",
    image: imageUrl,
    salary: "$70,000",
    posted: "2024-01-15",
  },
  {
    companyName: "InnovateX",
    jobRole: "UI/UX Designer",
    contract: "Part-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$65,000",
    posted: "2024-01-12",
  },
  {
    companyName: "DataSolutions",
    jobRole: "Data Scientist",
    contract: "Full-Time",
    place: "Austin, TX",
    image: imageUrl,
    salary: "$90,000",
    posted: "2024-01-10",
  },
  {
    companyName: "SoftWorks",
    jobRole: "Backend Developer",
    contract: "Full-Time",
    place: "Seattle, WA",
    image: imageUrl,
    salary: "$75,000",
    posted: "2024-01-08",
  },
  {
    companyName: "DesignStudio",
    jobRole: "Graphic Designer",
    contract: "Freelance",
    place: "Remote",
    image: imageUrl,
    salary: "$60,000",
    posted: "2024-01-05",
  },
  {
    companyName: "SecureTech",
    jobRole: "Security Analyst",
    contract: "Full-Time",
    place: "Washington, D.C.",
    image: imageUrl,
    salary: "$80,000",
    posted: "2024-01-02",
  },
  {
    companyName: "HealthTech",
    jobRole: "Software Engineer",
    contract: "Full-Time",
    place: "Boston, MA",
    image: imageUrl,
    salary: "$85,000",
    posted: "2024-01-01",
  },
  {
    companyName: "GreenEnergy",
    jobRole: "Project Manager",
    contract: "Full-Time",
    place: "Denver, CO",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-12-30",
  },
  {
    companyName: "FinTech",
    jobRole: "Business Analyst",
    contract: "Full-Time",
    place: "Chicago, IL",
    image: imageUrl,
    salary: "$70,000",
    posted: "2023-12-28",
  },
  {
    companyName: "EduTech",
    jobRole: "Product Manager",
    contract: "Full-Time",
    place: "Los Angeles, CA",
    image: imageUrl,
    salary: "$90,000",
    posted: "2023-12-25",
  },
  {
    companyName: "TechSolutions",
    jobRole: "Software Developer",
    contract: "Full-Time",
    place: "San Diego, CA",
    image: imageUrl,
    salary: "$80,000",
    posted: "2023-12-23",
  },
  {
    companyName: "MediaTech",
    jobRole: "Media Analyst",
    contract: "Part-Time",
    place: "Miami, FL",
    image: imageUrl,
    salary: "$55,000",
    posted: "2023-12-20",
  },
  {
    companyName: "CloudWorks",
    jobRole: "Cloud Architect",
    contract: "Full-Time",
    place: "Dallas, TX",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-12-18",
  },
  {
    companyName: "BioTech",
    jobRole: "Biomedical Engineer",
    contract: "Full-Time",
    place: "Philadelphia, PA",
    image: imageUrl,
    salary: "$85,000",
    posted: "2023-12-15",
  },
  {
    companyName: "ConsultingHub",
    jobRole: "Consultant",
    contract: "Freelance",
    place: "Remote",
    image: imageUrl,
    salary: "$90,000",
    posted: "2023-12-13",
  },
  {
    companyName: "AI Technologies",
    jobRole: "AI Engineer",
    contract: "Full-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$110,000",
    posted: "2023-12-10",
  },
  {
    companyName: "E-commerce Solutions",
    jobRole: "E-commerce Manager",
    contract: "Full-Time",
    place: "Seattle, WA",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-12-08",
  },
  {
    companyName: "Virtual Reality Innovations",
    jobRole: "VR Developer",
    contract: "Full-Time",
    place: "Los Angeles, CA",
    image: imageUrl,
    salary: "$105,000",
    posted: "2023-12-05",
  },
  {
    companyName: "Robotics Inc.",
    jobRole: "Robotics Engineer",
    contract: "Full-Time",
    place: "Boston, MA",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-12-03",
  },
  {
    companyName: "Social Media Solutions",
    jobRole: "Social Media Manager",
    contract: "Full-Time",
    place: "New York, NY",
    image: imageUrl,
    salary: "$85,000",
    posted: "2023-11-30",
  },
  {
    companyName: "Blockchain Technologies",
    jobRole: "Blockchain Developer",
    contract: "Full-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$120,000",
    posted: "2023-11-28",
  },
  {
    companyName: "Game Development Studios",
    jobRole: "Game Developer",
    contract: "Full-Time",
    place: "Austin, TX",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-11-25",
  },
  {
    companyName: "Automotive Innovations",
    jobRole: "Automotive Engineer",
    contract: "Full-Time",
    place: "Detroit, MI",
    image: imageUrl,
    salary: "$90,000",
    posted: "2023-11-23",
  },
  {
    companyName: "FashionTech",
    jobRole: "Fashion Technologist",
    contract: "Full-Time",
    place: "New York, NY",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-11-20",
  },
  {
    companyName: "Cybersecurity Solutions",
    jobRole: "Cybersecurity Specialist",
    contract: "Full-Time",
    place: "Washington, D.C.",
    image: imageUrl,
    salary: "$110,000",
    posted: "2023-11-18",
  },
  {
    companyName: "Healthcare Innovations",
    jobRole: "Healthcare Data Analyst",
    contract: "Full-Time",
    place: "Chicago, IL",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-11-15",
  },
  {
    companyName: "Artificial Intelligence Solutions",
    jobRole: "AI Research Scientist",
    contract: "Full-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$130,000",
    posted: "2023-11-13",
  },
  {
    companyName: "Renewable Energy Solutions",
    jobRole: "Backend Engineer",
    contract: "Full-Time",
    place: "Denver, CO",
    image: imageUrl,
    salary: "$105,000",
    posted: "2023-11-10",
  },
  {
    companyName: "Education Technologies",
    jobRole: "EdTech Specialist",
    contract: "Full-Time",
    place: "Los Angeles, CA",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-11-08",
  },
  {
    companyName: "Telecommunications Innovations",
    jobRole: "Telecom Engineer",
    contract: "Full-Time",
    place: "Dallas, TX",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-11-05",
  },
  {
    companyName: "Financial Technologies",
    jobRole: "FinTech Analyst",
    contract: "Full-Time",
    place: "New York, NY",
    image: imageUrl,
    salary: "$110,000",
    posted: "2023-11-03",
  },
  {
    companyName: "Environmental Technologies",
    jobRole: "Environmental Engineer",
    contract: "Full-Time",
    place: "Seattle, WA",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-10-30",
  },
  {
    companyName: "Space Technologies",
    jobRole: "Space Systems Engineer",
    contract: "Full-Time",
    place: "Houston, TX",
    image: imageUrl,
    salary: "$120,000",
    posted: "2023-10-28",
  },
  {
    companyName: "Advertising Innovations",
    jobRole: "Advertising Specialist",
    contract: "Full-Time",
    place: "Chicago, IL",
    image: imageUrl,
    salary: "$90,000",
    posted: "2023-10-25",
  },
  {
    companyName: "Digital Marketing Solutions",
    jobRole: "Tech Manager",
    contract: "Full-Time",
    place: "Los Angeles, CA",
    image: imageUrl,
    salary: "$105,000",
    posted: "2023-10-23",
  },
  {
    companyName: "Automated Systems",
    jobRole: "Automation Engineer",
    contract: "Full-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$115,000",
    posted: "2023-10-20",
  },
  {
    companyName: "Biotechnology Innovations",
    jobRole: "Biotech Scientist",
    contract: "Full-Time",
    place: "Boston, MA",
    image: imageUrl,
    salary: "$110,000",
    posted: "2023-10-18",
  },
  {
    companyName: "Healthcare Technologies",
    jobRole: "HealthTech Engineer",
    contract: "Full-Time",
    place: "Washington, D.C.",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-10-15",
  },
  {
    companyName: "Gaming Technologies",
    jobRole: "Game Dev Engineer",
    contract: "Full-Time",
    place: "Seattle, WA",
    image: imageUrl,
    salary: "$95,000",
    posted: "2023-10-13",
  },
  {
    companyName: "Virtual Reality Solutions",
    jobRole: "VR UX Designer",
    contract: "Full-Time",
    place: "Los Angeles, CA",
    image: imageUrl,
    salary: "$110,000",
    posted: "2023-10-10",
  },
  {
    companyName: "Blockchain Innovations",
    jobRole: "Blockchain Architect",
    contract: "Full-Time",
    place: "New York, NY",
    image: imageUrl,
    salary: "$120,000",
    posted: "2023-10-08",
  },
  {
    companyName: "Social Media Technologies",
    jobRole: "Social Media Analyst",
    contract: "Full-Time",
    place: "San Francisco, CA",
    image: imageUrl,
    salary: "$100,000",
    posted: "2023-10-05",
  },
  {
    companyName: "AI Development",
    jobRole: "AI Software Engineer",
    contract: "Full-Time",
    place: "Seattle, WA",
    image: imageUrl,
    salary: "$115,000",
    posted: "2023-10-03",
  },
  {
    companyName: "Cloud Computing Solutions",
    jobRole: "Cloud Solutions Architect",
    contract: "Full-Time",
    place: "Austin, TX",
    image: imageUrl,
    salary: "$125,000",
    posted: "2023-10-01",
  },
];

export default JobFakeData;
