const imageUrl = "https://fakeimg.pl/270x270";

const ProfileFakeData = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "123-456-7890",
    githubLink: "https://github.com/johndoe",
    course: "Software Engineering Bootcamp",
    image: imageUrl,
    year: "2023",
    specialist: "Backend Engineer",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "123-456-7891",
    githubLink: "https://github.com/janesmith",
    course: "User Experience Design Bootcamp",
    image: imageUrl,
    year: "2022",
    specialist: "UI/UX Designer",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phoneNumber: "123-456-7892",
    githubLink: "https://github.com/michaeljohnson",
    course: "Data Analytics Bootcamp",
    image: imageUrl,
    year: "2023",
    specialist: "Data Analyst",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    phoneNumber: "123-456-7893",
    githubLink: "https://github.com/emilydavis",
    course: "React Development Short Course",
    image: imageUrl,
    year: "2021",
    specialist: "Frontend Engineer",
  },
  {
    firstName: "Daniel",
    lastName: "Brown",
    email: "daniel.brown@example.com",
    phoneNumber: "123-456-7894",
    githubLink: "https://github.com/danielbrown",
    course: "Python Programming Short Course",
    image: imageUrl,
    year: "2020",
    specialist: "Data Scientist",
  },
  {
    firstName: "Olivia",
    lastName: "Wilson",
    email: "olivia.wilson@example.com",
    phoneNumber: "123-456-7895",
    githubLink: "https://github.com/oliviawilson",
    course: "User Experience Design Short Course",
    image: imageUrl,
    year: "2019",
    specialist: "UI/UX Designer",
  },
  {
    firstName: "William",
    lastName: "Martinez",
    email: "william.martinez@example.com",
    phoneNumber: "123-456-7896",
    githubLink: "https://github.com/williammartinez",
    course: "Frontend Web Development Short Course",
    image: imageUrl,
    year: "2021",
    specialist: "Frontend Engineer",
  },
  {
    firstName: "Sophia",
    lastName: "Anderson",
    email: "sophia.anderson@example.com",
    phoneNumber: "123-456-7897",
    githubLink: "https://github.com/sophiaanderson",
    course: "Digital Marketing Short Course",
    image: imageUrl,
    year: "2020",
    specialist: "Marketing Specialist",
  },
  {
    firstName: "James",
    lastName: "Taylor",
    email: "james.taylor@example.com",
    phoneNumber: "123-456-7898",
    githubLink: "https://github.com/jamestaylor",
    course: "Data Science Bootcamp",
    image: imageUrl,
    year: "2023",
    specialist: "Data Scientist",
  },
  {
    firstName: "Ava",
    lastName: "Moore",
    email: "ava.moore@example.com",
    phoneNumber: "123-456-7899",
    githubLink: "https://github.com/avamoore",
    course: "Product Management Short Course",
    image: imageUrl,
    year: "2022",
    specialist: "Product Manager",
  },
  {
    firstName: "Henry",
    lastName: "Lee",
    email: "henry.lee@example.com",
    phoneNumber: "123-456-7800",
    githubLink: "https://github.com/henrylee",
    course: "Software Engineering Bootcamp (Part-time)",
    image: imageUrl,
    year: "2021",
    specialist: "Fullstack Engineer",
  },
  {
    firstName: "Isabella",
    lastName: "Garcia",
    email: "isabella.garcia@example.com",
    phoneNumber: "123-456-7801",
    githubLink: "https://github.com/isabellagarcia",
    course: "Data Science Bootcamp (Part-time)",
    image: imageUrl,
    year: "2023",
    specialist: "Data Scientist",
  },
  {
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    phoneNumber: "123-456-7802",
    githubLink: "https://github.com/davidmartinez",
    course: "User Experience Design Bootcamp (Part-time)",
    image: imageUrl,
    year: "2020",
    specialist: "UI/UX Designer",
  },
  {
    firstName: "Charlotte",
    lastName: "Hernandez",
    email: "charlotte.hernandez@example.com",
    phoneNumber: "123-456-7803",
    githubLink: "https://github.com/charlottehernandez",
    course: "Data Analytics Bootcamp (Part-time)",
    image: imageUrl,
    year: "2019",
    specialist: "Data Analyst",
  },
  {
    firstName: "Lucas",
    lastName: "Lopez",
    email: "lucas.lopez@example.com",
    phoneNumber: "123-456-7804",
    githubLink: "https://github.com/lucaslopez",
    course: "JavaScript Development Short Course",
    image: imageUrl,
    year: "2022",
    specialist: "Frontend Engineer",
  },
  {
    firstName: "Mia",
    lastName: "Gonzalez",
    email: "mia.gonzalez@example.com",
    phoneNumber: "123-456-7805",
    githubLink: "https://github.com/miagonzalez",
    course: "Visual Design Short Course",
    image: imageUrl,
    year: "2021",
    specialist: "UI/UX Designer",
  },
  {
    firstName: "Ethan",
    lastName: "Wilson",
    email: "ethan.wilson@example.com",
    phoneNumber: "123-456-7806",
    githubLink: "https://github.com/ethanwilson",
    course: "Digital Marketing Short Course",
    image: imageUrl,
    year: "2020",
    specialist: "Marketing Specialist",
  },
  {
    firstName: "Amelia",
    lastName: "Moore",
    email: "amelia.moore@example.com",
    phoneNumber: "123-456-7807",
    githubLink: "https://github.com/ameliamoore",
    course: "Frontend Web Development Short Course",
    image: imageUrl,
    year: "2023",
    specialist: "Frontend Engineer",
  },
  {
    firstName: "Mason",
    lastName: "Thomas",
    email: "mason.thomas@example.com",
    phoneNumber: "123-456-7808",
    githubLink: "https://github.com/masonthomas",
    course: "React Development Short Course",
    image: imageUrl,
    year: "2022",
    specialist: "Frontend Engineer",
  },
  {
    firstName: "Harper",
    lastName: "Martinez",
    email: "harper.martinez@example.com",
    phoneNumber: "123-456-7809",
    githubLink: "https://github.com/harpermartinez",
    course: "Product Management Short Course",
    image: imageUrl,
    year: "2021",
    specialist: "Product Manager",
  },
  {
    firstName: "Alex",
    lastName: "Hamilton",
    email: "alex-hamilton@example.com",
    phoneNumber: "123-456-7809",
    githubLink: "https://github.com/alexhamilton",
    course: "Data Science Bootcamp",
    image: imageUrl,
    year: "2021",
    specialist: "Financial Engineer",
  },
];

export default ProfileFakeData;
