const imageUrl = "https://fakeimg.pl/270x270";
const ProfileFakeData = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "123-456-7890",
    githubLink: "https://github.com/johndoe",
    course: "Software Engineering",
    image: imageUrl,
    year: "2023",
    specialist: "Backend Engineer",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "123-456-7891",
    githubLink: "https://github.com/janesmith",
    course: "User Experience Design",
    image: imageUrl,
    year: "2022",
    specialist: "UI/UX Designer",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phoneNumber: "123-456-7892",
    githubLink: "https://github.com/michaeljohnson",
    course: "Data Analytics",
    image: imageUrl,
    year: "2023",
    specialist: "Data Analyst",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    phoneNumber: "123-456-7893",
    githubLink: "https://github.com/emilydavis",
    course: "Software Engineering",
    image: imageUrl,
    year: "2022",
    specialist: "Frontend Developer",
  },
  {
    firstName: "Daniel",
    lastName: "Brown",
    email: "daniel.brown@example.com",
    phoneNumber: "123-456-7894",
    githubLink: "https://github.com/danielbrown",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "UI Designer",
  },
  {
    firstName: "Jessica",
    lastName: "Wilson",
    email: "jessica.wilson@example.com",
    phoneNumber: "123-456-7895",
    githubLink: "https://github.com/jessicawilson",
    course: "Data Analytics",
    image: imageUrl,
    year: "2020",
    specialist: "Data Scientist at BikeDance",
  },
  {
    firstName: "David",
    lastName: "Miller",
    email: "david.miller@example.com",
    phoneNumber: "123-456-7896",
    githubLink: "https://github.com/davidmiller",
    course: "Software Engineering",
    image: imageUrl,
    year: "2019",
    specialist: "Backend Developer at MCS",
  },
  {
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@example.com",
    phoneNumber: "123-456-7897",
    githubLink: "https://github.com/sophiamartinez",
    course: "User Experience Design",
    image: imageUrl,
    year: "2019",
    specialist: "UI Manager at Sainypse",
  },
  {
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    phoneNumber: "123-456-7898",
    githubLink: "https://github.com/jamesanderson",
    course: "Data Analytics",
    image: imageUrl,
    year: "2018",
    specialist: "Data Engineer at TicketMuster",
  },
  {
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    phoneNumber: "123-456-7899",
    githubLink: "https://github.com/oliviataylor",
    course: "Software Engineering",
    image: imageUrl,
    year: "2017",
    specialist: "Backend Engineering Lead at Dadas",
  },
  {
    firstName: "William",
    lastName: "Moore",
    email: "william.moore@example.com",
    phoneNumber: "123-456-7800",
    githubLink: "https://github.com/williampoore",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Fullstack Developer",
  },
  {
    firstName: "Ava",
    lastName: "Harris",
    email: "ava.harris@example.com",
    phoneNumber: "123-456-7801",
    githubLink: "https://github.com/avaharris",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "UX Researcher",
  },
  {
    firstName: "Alexander",
    lastName: "Hamilton",
    email: "alexander.hamilton@example.com",
    phoneNumber: "123-456-7802",
    githubLink: "https://github.com/alexanderhamilton",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Financial Engineer",
  },
  {
    firstName: "Isabella",
    lastName: "Garcia",
    email: "isabella.garcia@example.com",
    phoneNumber: "123-456-7803",
    githubLink: "https://github.com/isabellagarcia",
    course: "Software Engineering",
    image: imageUrl,
    year: "2018",
    specialist: "DevOps Engineer",
  },
  {
    firstName: "Benjamin",
    lastName: "Martinez",
    email: "benjamin.martinez@example.com",
    phoneNumber: "123-456-7804",
    githubLink: "https://github.com/benjaminmartinez",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "Interaction Designer",
  },
  {
    firstName: "Charlotte",
    lastName: "Clark",
    email: "charlotte.clark@example.com",
    phoneNumber: "123-456-7805",
    githubLink: "https://github.com/charlotteclark",
    course: "Data Analytics",
    image: imageUrl,
    year: "2022",
    specialist: "Business Intelligence Analyst",
  },
  {
    firstName: "Henry",
    lastName: "Rodriguez",
    email: "henry.rodriguez@example.com",
    phoneNumber: "123-456-7806",
    githubLink: "https://github.com/henryrodriguez",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Cloud Engineer",
  },
  {
    firstName: "Amelia",
    lastName: "Lewis",
    email: "amelia.lewis@example.com",
    phoneNumber: "123-456-7807",
    githubLink: "https://github.com/amelialewis",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "Visual Designer",
  },
  {
    firstName: "Elijah",
    lastName: "Walker",
    email: "elijah.walker@example.com",
    phoneNumber: "123-456-7808",
    githubLink: "https://github.com/elijahwalker",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Data Engineer",
  },
  {
    firstName: "Mia",
    lastName: "Young",
    email: "mia.young@example.com",
    phoneNumber: "123-456-7809",
    githubLink: "https://github.com/miayoung",
    course: "Software Engineering",
    image: imageUrl,
    year: "2018",
    specialist: "Mobile Developer",
  },
  {
    firstName: "Lucas",
    lastName: "Allen",
    email: "lucas.allen@example.com",
    phoneNumber: "123-456-7810",
    githubLink: "https://github.com/lucasallen",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "Product Designer",
  },
  {
    firstName: "Mason",
    lastName: "King",
    email: "mason.king@example.com",
    phoneNumber: "123-456-7811",
    githubLink: "https://github.com/masonking",
    course: "Data Analytics",
    image: imageUrl,
    year: "2022",
    specialist: "Data Visualization Specialist",
  },
  {
    firstName: "Evelyn",
    lastName: "Wright",
    email: "evelyn.wright@example.com",
    phoneNumber: "123-456-7812",
    githubLink: "https://github.com/evelynwright",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Software Architect",
  },
  {
    firstName: "Logan",
    lastName: "Scott",
    email: "logan.scott@example.com",
    phoneNumber: "123-456-7813",
    githubLink: "https://github.com/loganscott",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "UX/UI Developer",
  },
  {
    firstName: "Harper",
    lastName: "Torres",
    email: "harper.torres@example.com",
    phoneNumber: "123-456-7814",
    githubLink: "https://github.com/harpertorres",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Data Scientist",
  },
  {
    firstName: "Jackson",
    lastName: "Bennett",
    email: "jackson.bennett@example.com",
    phoneNumber: "123-456-7815",
    githubLink: "https://github.com/jacksonbennett",
    course: "Software Engineering",
    image: imageUrl,
    year: "2018",
    specialist: "Systems Engineer",
  },
  {
    firstName: "Scarlett",
    lastName: "Jenkins",
    email: "scarlett.jenkins@example.com",
    phoneNumber: "123-456-7816",
    githubLink: "https://github.com/scarlettjenkins",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "Design Strategist",
  },
  {
    firstName: "Liam",
    lastName: "Perry",
    email: "liam.perry@example.com",
    phoneNumber: "123-456-7817",
    githubLink: "https://github.com/liamperry",
    course: "Data Analytics",
    image: imageUrl,
    year: "2022",
    specialist: "Big Data Engineer",
  },
  {
    firstName: "Emma",
    lastName: "Stewart",
    email: "emma.stewart@example.com",
    phoneNumber: "123-456-7818",
    githubLink: "https://github.com/emmastuart",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Software Developer",
  },
  {
    firstName: "Olivia",
    lastName: "Brooks",
    email: "olivia.brooks@example.com",
    phoneNumber: "123-456-7819",
    githubLink: "https://github.com/oliviabrooks",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "UX Consultant",
  },
  {
    firstName: "Ethan",
    lastName: "Foster",
    email: "ethan.foster@example.com",
    phoneNumber: "123-456-7820",
    githubLink: "https://github.com/ethanfoster",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Data Miner",
  },
  {
    firstName: "Sophia",
    lastName: "Griffin",
    email: "sophia.griffin@example.com",
    phoneNumber: "123-456-7821",
    githubLink: "https://github.com/sophiagriffin",
    course: "Software Engineering",
    image: imageUrl,
    year: "2018",
    specialist: "AI Engineer",
  },
  {
    firstName: "James",
    lastName: "Hughes",
    email: "james.hughes@example.com",
    phoneNumber: "123-456-7822",
    githubLink: "https://github.com/jameshughes",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "UX Specialist",
  },
  {
    firstName: "Isabella",
    lastName: "Morgan",
    email: "isabella.morgan@example.com",
    phoneNumber: "123-456-7823",
    githubLink: "https://github.com/isabellamorgan",
    course: "Data Analytics",
    image: imageUrl,
    year: "2022",
    specialist: "Data Consultant",
  },
  {
    firstName: "Lucas",
    lastName: "Mitchell",
    email: "lucas.mitchell@example.com",
    phoneNumber: "123-456-7824",
    githubLink: "https://github.com/lucasmitchell",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Embedded Systems Engineer",
  },
  {
    firstName: "Ava",
    lastName: "Hill",
    email: "ava.hill@example.com",
    phoneNumber: "123-456-7825",
    githubLink: "https://github.com/avahill",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "UX Writer",
  },
  {
    firstName: "Mason",
    lastName: "Green",
    email: "mason.green@example.com",
    phoneNumber: "123-456-7826",
    githubLink: "https://github.com/masongreen",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Database Administrator",
  },
  {
    firstName: "Harper",
    lastName: "Adams",
    email: "harper.adams@example.com",
    phoneNumber: "123-456-7827",
    githubLink: "https://github.com/harperadams",
    course: "Software Engineering",
    image: imageUrl,
    year: "2018",
    specialist: "Cybersecurity Analyst",
  },
  {
    firstName: "Evelyn",
    lastName: "Baker",
    email: "evelyn.baker@example.com",
    phoneNumber: "123-456-7828",
    githubLink: "https://github.com/evelynbaker",
    course: "User Experience Design",
    image: imageUrl,
    year: "2023",
    specialist: "Service Designer",
  },
  {
    firstName: "Logan",
    lastName: "Nelson",
    email: "logan.nelson@example.com",
    phoneNumber: "123-456-7829",
    githubLink: "https://github.com/logannelson",
    course: "Data Analytics",
    image: imageUrl,
    year: "2022",
    specialist: "Quantitative Analyst",
  },
  {
    firstName: "Charlotte",
    lastName: "Carter",
    email: "charlotte.carter@example.com",
    phoneNumber: "123-456-7830",
    githubLink: "https://github.com/charlottecarter",
    course: "Software Engineering",
    image: imageUrl,
    year: "2021",
    specialist: "Solutions Architect",
  },
  {
    firstName: "Henry",
    lastName: "Reed",
    email: "henry.reed@example.com",
    phoneNumber: "123-456-7831",
    githubLink: "https://github.com/henryreed",
    course: "User Experience Design",
    image: imageUrl,
    year: "2020",
    specialist: "Creative Director",
  },
  {
    firstName: "Isabella",
    lastName: "Gonzalez",
    email: "isabella.gonzalez@example.com",
    phoneNumber: "123-456-7832",
    githubLink: "https://github.com/isabellagonzalez",
    course: "Data Analytics",
    image: imageUrl,
    year: "2019",
    specialist: "Operations Analyst",
  },
];

export default ProfileFakeData;
